# Asset Pricing Machine Configuration
# All TODO values must be filled before running the analysis

project:
  country: Germany
  base_currency: EUR
  timezone: Europe/Berlin
  start_date: "2015-01-01"
  end_date: "2024-12-31"
  frequency: M
  seed: 42

universe:
  method: static_list   # or top_n_mcap
  min_obs_months: 24
  allow_unbalanced: true
  path_static_list: data/raw/stocks/   # folder with 25 CSVs (one per stock)

benchmarks:
  market_index: index_csv
  risk_model: both      # options: rf_capm, zero_beta, both
  risk_free_source: data/raw/risk_free/rf_eur.csv
  index_csv: data/raw/market/dax_tr.csv

paths:
  risk_free_csv: data/raw/risk_free/rf_eur.csv
  fundamentals_csv: data/raw/fundamentals.csv  # optional B/M; leave if unknown
  market_caps_csv: input/marketcaps_asof.csv  # VW weights from yfinance

regression:
  nw_lags: 4
  winsorize_pct: 0.01

optimization:
  allow_shorting: false
  weight_bounds: [0.0, 0.25]
  covariance_estimator: ledoit_wolf

value_effect:
  enabled: false       # set true if fundamentals provided
  bm_lag_months: 6
  sort_breakpoints: tertiles

outputs:
  dir: output
